### PR TITLE
Adds playerIsGM function and Macro object

### PR DESCRIPTION
**Pull request by LaytonGB**

### CODE REVIEW

**Comment by Carl-Hugo** [comment]
Thanks, I'll trust that the signatures are all ok and thanks to the "Hide whitespace" option, you seem to have changed the end of lines character(s).
image
This should close #1

**Comment by LaytonGB** [comment]
Yeah, the whitespaces were giving me real hassle. This was my first Pull Request so I'm sorry for that, it's inexperience showing. Thanks for getting everything sorted so fast.

**Comment by Carl-Hugo** [comment]
> Yeah, the whitespaces were giving me real hassle. This was my first Pull Request so I'm sorry for that, it's inexperience showing. Thanks for getting everything sorted so fast.

@LaytonGB everyone starts somewhere ;)

That said, you should be able to configure your Git to checking/checkout the source code the way you want. I could also have included a `.gitattributes` file in the repository to define that. See [Configuring Git to handle line endings](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) for more info.

Locally, you can also change that in your code editor, I use Visual Studio Code, which allows you to do that very easily, like this:
1. image
1. image

But how your git client handles that is the more important, as it could change lines ending when committing changes 😉

**Comment by LaytonGB** [comment]
Thanks! I wasn't expecting such a helpful reply, and I couldn't appreciate it more. Hopefully I'll have it down in future.

**Pull request merged**
